### ISSUE TITLE
http-servlet RA deployment failure

### ISSUE THREAD

**Issue by mahmudemam** [RestComm/jain-slee.http#16]
Hi,

My environment is:
SLEE: restcomm-slee-7.1.77.80-wildfly-10.1.0.Final
HTTP: restcomm-slee-ra-http-servlet-DU-7.1.18.jar

I got the following error while trying to deploy http-servlet RA on the mentioned SLEE version:
`10:12:38,359 ERROR [org.mobicents.slee.container.deployment.jboss.DeploymentManager] (MSC service thread 1-6) Failure invoking 'InstallDeployableUnitAction[file:/dev_apps/restcomm/restcomm-slee-7.1.77.80-wildfly-10.1.0.Final/wildfly-10.1.0.Final/standalone/tmp/vfs/temp/tempfcfe1aebac435879/content-3760cc2e2149a140/content/]: javax.slee.management.DeploymentException: Failure encountered during deploy process.
	at org.mobicents.slee.container.management.jmx.DeploymentMBeanImpl.install(DeploymentMBeanImpl.java:340)
	at org.mobicents.slee.container.deployment.jboss.action.InstallDeployableUnitAction.invoke(InstallDeployableUnitAction.java:41)
	at org.mobicents.slee.container.deployment.jboss.DeploymentManager.sciAction(DeploymentManager.java:316)
	at org.mobicents.slee.container.deployment.jboss.DeploymentManager.installDeployableUnit(DeploymentManager.java:161)
	at org.mobicents.slee.container.deployment.jboss.SLEESubDeployer.start(SLEESubDeployer.java:278)
	at org.mobicents.slee.container.deployment.jboss.SleeContainerDeployerImpl.start(SleeContainerDeployerImpl.java:264)
	at org.restcomm.slee.container.build.as7.deployment.ExternalDeployerImpl.callSubDeployer(ExternalDeployerImpl.java:186)
	at org.restcomm.slee.container.build.as7.deployment.ExternalDeployerImpl.deploy(ExternalDeployerImpl.java:136)
	at org.restcomm.slee.container.build.as7.deployment.SleeDeploymentInstallProcessor.deploy(SleeDeploymentInstallProcessor.java:46)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.slee.management.DeploymentException: Component ResourceAdaptorID[name=HttpServletResourceAdaptor,vendor=org.restcomm,version=1.0] requires a class that was not found
	at org.mobicents.slee.container.component.deployment.DeployableUnitBuilderImpl.loadAndSetNonGeneratedComponentClasses(DeployableUnitBuilderImpl.java:524)
	at org.mobicents.slee.container.component.deployment.DeployableUnitBuilderImpl.build(DeployableUnitBuilderImpl.java:236)
	at org.mobicents.slee.container.component.deployment.DeployableUnitBuilderImpl.build(DeployableUnitBuilderImpl.java:72)
	at org.mobicents.slee.container.management.jmx.DeploymentMBeanImpl.install(DeploymentMBeanImpl.java:164)
	... 14 more
Caused by: java.lang.NoClassDefFoundError: org/restcomm/slee/resource/http/HttpServletResourceEntryPoint
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at org.mobicents.slee.container.component.deployment.classloading.URLClassLoaderDomainImpl.findClassLocallyLocked(URLClassLoaderDomainImpl.java:272)
	at org.mobicents.slee.container.component.deployment.classloading.URLClassLoaderDomainImpl.findClass(URLClassLoaderDomainImpl.java:241)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.mobicents.slee.container.component.deployment.classloading.URLClassLoaderDomainImpl.loadClass(URLClassLoaderDomainImpl.java:200)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.mobicents.slee.container.component.deployment.DeployableUnitBuilderImpl.loadAndSetNonGeneratedComponentClasses(DeployableUnitBuilderImpl.java:452)
	... 17 more
Caused by: java.lang.ClassNotFoundException: org.restcomm.slee.resource.http.HttpServletResourceEntryPoint
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at org.mobicents.slee.container.component.deployment.classloading.URLClassLoaderDomainImpl.findClassLocallyLocked(URLClassLoaderDomainImpl.java:272)
	at org.mobicents.slee.container.component.deployment.classloading.URLClassLoaderDomainImpl.findClass(URLClassLoaderDomainImpl.java:241)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.mobicents.slee.container.component.deployment.classloading.URLClassLoaderDomainImpl.loadClass(URLClassLoaderDomainImpl.java:200)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more
`

Also, I've tried the 7.0.0-SNAPSHOT version and without any progress.

**Comment by vetss** [comment]
Hello @mahmudemam 

have you aslo deployed smpp-extension stack binaries (see https://github.com/RestComm/smpp-extensions) ? SMPP RA demands smpp-extension stack deployed for its work.

**Comment by mahmudemam** [comment]
why should I deploy SMPP RA?

**Comment by vetss** [comment]
@mahmudemam 
Sorry, I messed two RAs (SMPP / HTTP)

**Comment by mahmudemam** [comment]
I don't understand you, do you mean that it is required to deploy SMPP to make HTTP work?

**Comment by mahmudemam** [comment]
@deruelle 
Do you know that error or assign any one for that URGENTLY?

**Comment by deruelle** [comment]
@mahmudemam we don't treat anything in community as URGENTLY it's best effort support. If you need URGENT help please contact sales at telestax dot com

**Comment by olenara** [comment]
Hello @mahmudemam.
The reason of error is that restcomm-slee-ra-http-servlet-common.jar has not been deployed. In wildfly10 it is deployed as module. For this please follow the steps:
1. set $JBOSS_HOME to point to /.../restcomm-slee-7.2.0-68.76-wildfly-10.1.0.Final/wildfly-10.1.0.Final
2. cd to extra/restcomm-http and run 'ant deploy' command there.

**Comment by gmainerd** [comment]
I have the same problem:
-restcomm-slee-7.2.0-wildfly-10.1.0.Final
-restcomm-slee-ra-http-servlet-common.jar
-restcomm-slee-ra-http-servlet-DU-7.1.18.jar

I do a "ant deploy" and it seems to deploy the common lib and then the DU but after this is deployed it throws the class not found exception. Do I need to deploy in a different way?

**Comment by gsaslis** [comment]
@gmainerd perhaps you can share logs (as a [gist](https://gist.github.com/) plz ;) ) and steps to reproduce ?

**Comment by gmainerd** [comment]
Thank you for your reply, I solved the issue adding the module as a dependency on the SLEE container, editing this file:
modules/system/layers/base/org/restcomm/slee/container/lib/main/module.xml
with 
`<module name="org.restcomm.slee.resource.http.common" export="true"/>`
After that I managed to deploy correctly the RA without the exception.
